# Generated by Django 5.1.4 on 2025-03-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=255)),
                ('question_mark', models.IntegerField(default=0)),
                ('question_levels', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division_no', models.IntegerField(default=1)),
                ('division_title', models.CharField(max_length=255)),
                ('division_mark', models.IntegerField(default=0)),
                ('mark_per_question', models.IntegerField(default=0)),
                ('extra_question', models.IntegerField(default=0)),
                ('status', models.CharField(default='Incomplete', max_length=100)),
                ('division_questions', models.ManyToManyField(blank=True, related_name='divisions', to='Questions.question')),
            ],
            options={
                'db_table': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_paper_type', models.CharField(max_length=20)),
                ('question_paper_title', models.CharField(max_length=255)),
                ('question_paper_total_marks', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=1)),
                ('academic_year_start', models.IntegerField(default=2024)),
                ('academic_year_end', models.PositiveIntegerField(default=2025)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Incomplete', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('divisions', models.ManyToManyField(related_name='question_papers', to='Questions.division')),
                ('question_paper_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='Users.subject')),
            ],
            options={
                'db_table': 'Question Papers',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(default=0)),
                ('unit_title', models.CharField(max_length=255)),
                ('co', models.IntegerField(default=0)),
                ('co_title', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='question_sets', to='Questions.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='Users.subject')),
            ],
            options={
                'db_table': 'Question Sets',
            },
        ),
    ]
